version: 2
updates:
- package-ecosystem: pip
  allow:
    - dependency-type: all
  commit-message:
    prefix: Bug 2041558 - deps
  cooldown:
    default-days: 7
  directory: "/"
  groups:
    production-dependencies:
      applies-to: version-updates
      dependency-type: "production"
      update-types:
          - patch
          - minor
    development-dependencies:
      applies-to: version-updates
      dependency-type: "development"
  open-pull-requests-limit: 99
  schedule:
    interval: monthly
- package-ecosystem: "github-actions"
  commit-message:
    prefix: Bug 2041558 - workflows
  cooldown:
    default-days: 7
  directory: "/"
  groups:
    workflows:
      applies-to: version-updates
      update-types:
          - major
          - patch
          - minor
  schedule:
    interval: monthly
