[pulse]
# Those parameters can be overriden by PULSE_* environment variables
host = "pulse.mozilla.org"
port = 5671
ssl = true
userid = "SET THIS IN PULSE_USERID ENV VARIABLE"
password = "SET THIS IN PULSE_PASSWORD ENV VARIABLE"
# The exchange is declared by the Producer.
exchange = "exchange/landoprod/pushes"
routing_key = "gitpushes"
# The Consumer declares the queue and binds it to the exchange.
heartbeat = 30
queue = "queue/githgsyncprod/pushes"

[sentry]
sentry_dsn = ""

[clones]
directory = "/clones"

#################
# INFRA-TESTING #
#################

[[tracked_repositories]]
name = "infra-testing"
url = "https://github.com/mozilla-firefox/infra-testing.git"

#
# MOZILLA-UNIFIED
#
# We don't sync to this repository, but we put it here first to fetch all
# references early, with the benefit of bundles.
#
# XXX: For this to work, https://github.com/mozilla-firefox/infra-testing.git needs
# to have all commits presents on https://github.com/mozilla-firefox/firefox.git.
#
[[branch_mappings]]
source_url = "https://github.com/mozilla-firefox/infra-testing.git"
branch_pattern = "THIS_SHOULD_MATCH_NOTHING"
destination_url = "https://hg.mozilla.org/mozilla-unified/"
destination_branch = "NOT_A_VALID_BRANCH"

[[branch_mappings]]
source_url = "https://github.com/mozilla-firefox/infra-testing.git"
branch_pattern = "autoland"
destination_url = "ssh://hg.mozilla.org/conduit-testing/infra-testing/"
destination_branch = "default"

# Relbranch syncing on infra-testing.
[[branch_mappings]]
source_url = "https://github.com/mozilla-firefox/infra-testing.git"
branch_pattern = "^((FIREFOX|DEVEDITION|FIREFOX-ANDROID)_(\\d+_\\d+_X)_RELBRANCH)$"
destination_url = "ssh://hg.mozilla.org/conduit-testing/infra-testing/"
destination_branch = "\\1"

[[tag_mappings]]
source_url = "https://github.com/mozilla-firefox/infra-testing.git"
tag_pattern = ".+"
destination_url = "ssh://hg.mozilla.org/conduit-testing/infra-testing/"
tags_destination_branch = "tags-testing"
# Default
#tag_message_suffix = "a=tagging CLOSED TREE DONTBUILD"


#####################
# REVIEW (MOZ-PHAB) #
#####################

[[tracked_repositories]]
name = "review"
url = "https://github.com/mozilla-conduit/review.git"

[[branch_mappings]]
source_url = "https://github.com/mozilla-conduit/review.git"
branch_pattern = ".+"
destination_url = "ssh://hg.mozilla.org/conduit-testing/review/"
destination_branch = "default"

[[tag_mappings]]
source_url = "https://github.com/mozilla-conduit/review.git"
tag_pattern = ".+"
destination_url = "ssh://hg.mozilla.org/conduit-testing/review/"
tags_destination_branch = "tags"
# Default
#tag_message_suffix = "a=tagging CLOSED TREE DONTBUILD"
