# This should be set via the environment
#[pulse]
#userid = "guest"
#host = "pulse"
#port = 5672
#exchange = "exchange/git-hg-sync/test"
#routing_key = "git-hg-sync"
#queue = "queue/git-hg-sync/sync"
#password = "guest"
#ssl = false

[sentry]
sentry_url = "FIXME"

[clones]
directory = "/clones"

[[tracked_repositories]]
name = "firefox"
url = "https://github.com/mozilla-firefox/firefox"

# M-C
[[branch_mappings]]
source_url = "https://github.com/mozilla-firefox/firefox"
branch_pattern = "main"
destination_url = "ssh://hg.mozilla.org//releases/mozilla-central/"
destination_branch = "default"

[[tag_mappings]]
source_url = "https://github.com/mozilla-firefox/firefox"
# BETA_<M> and NIGHTLY_<M> tags to m-c
tag_pattern = "^(FIREFOX|DEVEDITION|FIREFOX-ANDROID)_(BETA|NIGHTLY)_(\\d+)_(BASE|END)$"
destination_url = "ssh://hg.mozilla.org//releases/mozilla-central/"
tags_destination_branch = "tags"

# BETA
[[branch_mappings]]
source_url = "https://github.com/mozilla-firefox/firefox"
branch_pattern = "beta"
destination_url = "ssh://hg.mozilla.org//releases/mozilla-beta/"
destination_branch = "default"

[[tag_mappings]]
source_url = "https://github.com/mozilla-firefox/firefox"
# <M>_<m>(_<p>...)b<n> BUILD and RELEASE tags to mozilla-beta
tag_pattern = "^(FIREFOX|DEVEDITION|FIREFOX-ANDROID)_(\\d+(_\\d+)+)b\\d+_(BUILD\\d+|RELEASE)$"
destination_url = "ssh://hg.mozilla.org//releases/mozilla-beta/"
tags_destination_branch = "tags"

# RELEASE
[[branch_mappings]]
source_url = "https://github.com/mozilla-firefox/firefox"
branch_pattern = "release"
destination_url = "ssh://hg.mozilla.org//releases/mozilla-release/"
destination_branch = "default"

[[tag_mappings]]
source_url = "https://github.com/mozilla-firefox/firefox"
# <M>_<m>(_<p>...) BUILD and RELEASE tags to mozilla-release
tag_pattern = "^(FIREFOX|DEVEDITION|FIREFOX-ANDROID)_(\\d+(_\\d+)+)_(BUILD\\d+|RELEASE)$"
destination_url = "ssh://hg.mozilla.org//releases/mozilla-release/"
tags_destination_branch = "tags"

# ESRs
[[branch_mappings]]
source_url = "https://github.com/mozilla-firefox/firefox"
# esr<M> branches to mozilla-esr<M>
branch_pattern = "^(esr\\d+)$"
destination_url = "ssh://hg.mozilla.org//releases/mozilla-\\1/"
destination_branch = "default"

[[tag_mappings]]
source_url = "https://github.com/mozilla-firefox/firefox"
# <M>_<m>(_<p>...)esr BUILD and RELEASE tags to mozilla-esr<M>
tag_pattern = "^(FIREFOX|DEVEDITION|FIREFOX-ANDROID)_(\\d+)(_\\d+)+esr_(BUILD\\d+|RELEASE)$"
destination_url = "ssh://hg.mozilla.org//releases/mozilla-esr\\3/"
tags_destination_branch = "tags"

# AUTOLAND
[[branch_mappings]]
source_url = "https://github.com/mozilla-firefox/firefox"
branch_pattern = "autoland"
destination_url = "ssh://hg.mozilla.org//integration/autoland/"
destination_branch = "default"
