[pulse]
# Those parameters can be overriden by PULSE_* environment variables
host = "pulse.mozilla.org"
port = 5671
ssl = true
userid = "SET THIS IN PULSE_USERID ENV VARIABLE"
password = "SET THIS IN PULSE_PASSWORD ENV VARIABLE"
# The exchange is declared by the Producer.
exchange = "exchange/landoprod/pushes"
routing_key = "gitpushes.firefox"
# The Consumer declares the queue and binds it to the exchange.
heartbeat = 30
queue = "queue/githgsyncprod/pushes.firefox"

[sentry]
sentry_dsn = ""

[clones]
directory = "/clones"

###########
# FIREFOX #
###########

[[tracked_repositories]]
name = "firefox"
url = "https://github.com/mozilla-firefox/firefox.git_NOT_IN_USE"


#
# MOZILLA-UNIFIED
#
# We don't sync to this repository, but we put it here first to fetch all
# references early, with the benefit of bundles.
#
[[branch_mappings]]
source_url = "https://github.com/mozilla-firefox/firefox.git_NOT_IN_USE"
branch_pattern = "THIS_SHOULD_MATCH_NOTHING"
destination_url = "https://hg.mozilla.org/mozilla-unified/"
destination_branch = "NOT_A_VALID_BRANCH"

[[tag_mappings]]
source_url = "https://github.com/mozilla-firefox/firefox.git_NOT_IN_USE"
tag_pattern = "THIS_SHOULD_MATCH_NOTHING"
destination_url = "https://hg.mozilla.org/mozilla-unified/"
tags_destination_branch = "NOT_A_VALID_BRANCH"
# Default
#tag_message_suffix = "a=tagging CLOSED TREE DONTBUILD"
