name: Python

on:
  pull_request:
  push:
    branches: main

jobs:
  Pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pytest pytest-mock
          pip install -e .
          ./install_git-cinnabar.sh
          echo "${{ github.workspace }}" >> $GITHUB_PATH
      - name: Test with pytest
        run: |
          pytest --junitxml=pytest.xml 
