name: Tests & Lint

on:
  pull_request:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: create coverage folder
        run: |
          mkdir tests_output
          chmod a+w tests_output

      - name: Setup docker-compose
        uses: docker/setup-compose-action@v1

      - name: Build containers
        run: docker compose build

      - name: Execute tests in the running services
        run: |
          docker compose run --rm test --junitxml=pytest.xml
