name: Tests & Lint

on:
  pull_request:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: create coverage folder
        run: |
          mkdir tests_output
          chmod a+w tests_output

      - name: Setup docker-compose
        uses: docker/setup-compose-action@54042514f505b273907334ae2b9cdbb9a0213c1a # v2.4.0

      - name: Build containers
        run: docker compose build

      - name: Execute tests in the running services
        run: |
          docker compose run --rm test --junitxml=pytest.xml
